env:
  start: [0.0, 0.0]

agent:
  dynamics: 'bicycle' # "unicycle", "bicycle", "NH_intergrator" , "int"
  dim :
    ny : 2
    nx : 2
    nu : 1
  Dyn_gp_lengthscale :
    y1 : [5.2649, 4.5967, 7.0177] # y1 : [5.2649, 4.5967, 7.0177] #[2.6384, 2.5857, 2.5669]
    y2 : [3.9696, 2.1265, 6.6749] # y2 : [3.9696, 2.1265, 6.6749] #[2.1422, 2.7733, 2.1221]
    both : [[[5.2649, 4.5967, 7.0177]], [[3.9696, 2.1265, 6.6749]] ]
  Dyn_gp_noise : 7.0e-9
  Dyn_gp_outputscale : 
    y1 : 0.1040 #0.3040 #0.75  #0.65
    y2 : 0.1071 #0.3071 #0.65 #0.455, noise multiplier 3.0e-7 results in smooth trajectories
    both : [0.1040, 0.1071]
  Dyn_gp_task_noises : 
    val : [3.8, 1.27, 3.8, 1.27]
    multiplier : 3.0e-7                     #1.0e-5 Low noise value make it crazy fast
  Dyn_gp_beta : 3.0 # 1.5
  mean_shift_val : 2
  cov_module: 'Matern'     #'Matern', Sq_exp
  num_dyn_samples: 400
  prior_dyn_meas: True       
  mean_as_dyn_sample: False
  true_dyn_as_sample: False        # This is for debugging, set num_dyn_samples to 1

visu:
  show: True
  show_video: False
  show_current_loc: False

common:
  use_cuda : True
  num_MPC_itrs : 1

optimizer:
  H : 70 # horizon
  u_min : [-8] # Minimum control input
  u_max : [8] 
  # u_min : [-30, -30] # Minimum control input
  # u_max : [30, 30] 
  x_min : [-2.14, -2.5] # Minimum state value
  x_max : [ 2.14, 20] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 2
    tol_nlp: 1.0e-4 
  Tf: 1  # sampling time = Tf/H
  order: 2
  x_dim: 2
  dt: 0.015 # 0.010
  w: 50
  cost: "expected"               # "mean", "uncertainity", "expected"

experiment:
  name: "DEMPC" #
  GT_uncertainity : 
    propagate: True
    ref : '40'
  folder: "pendulum"
  rnd_seed: 
    use: True
    value: 123456