env:
  start: [0.0, 1.95, 0.0, 7.0] # x,y,theta,v
  goal_state: [70, 1.95, 0.0, 0.0]
  dynamics: 'bicycle_Bdx' # "pendulum"
  params: 
    lf: 1.105 #0.55 #1.105, 0.275
    lr: 1.738 #0.85 #1.738, 0.425
  prior_dyn_meas: True 
  train_data_has_derivatives: False
  n_data_x: 5
  n_data_u: 9
  ellipses:
    # n1 : [26, 5.0, 9.0, 1.0, 5.67]  # x0, y0, a^2, b^2, f equation of ellipse: (x-x0)^2/a^2 + (y-y0)^2/b^2 = f
    n1 : [15, 1.0, 9.0, 1.0, 5.67]
    # n3 : [42, 1.0, 9.0, 1.0, 5.67]
    # n4 : [58, 5.0, 9.0, 1.0, 5.67]
    # n1 : [24, 4.5, 9.0, 1.0, 5.67]  # x0, y0, a, b, f equation of ellipse: (x-x0)^2/a^2 + (y-y0)^2/b^2 = f
    # n2 : [10, 1.5, 9.0, 1.0, 5.67]
    # n3 : [38, 1.5, 9.0, 1.0, 5.67]
    # n4 : [52, 4.5, 9.0, 1.0, 5.67]

agent:
  g_dim :
    ny : 3
    nx : 1
    nu : 1
  dim :
    ny : 3
    nx : 4
    nu : 2
  Dyn_gp_lengthscale :
    # both : [[[0.21266, 0.56651, 1.05719]], [[2.2651, 4.6306, 7.6728]], [[20.9180, 6.1829, 3.7340]]]
    # both : [[[ 3.5447,  3.7175]], [[ 3.9424,  3.2711]], [[50.3278,  3.3770]]]
    both : [[[1.492, 1.508]], [[1.4, 1.1]], [[5.22931,  1.9544]]]
  Dyn_gp_noise : 1.0e-6 # zero noise (modulo GP jitter below)
  Dyn_gp_outputscale : 
    y1 : 0.1040 #0.3040 #0.75  #0.65
    y2 : 0.1071 #0.3071 #0.65 #0.455, noise multiplier 3.0e-7 results in smooth trajectories
    both : [0.065, 0.045, 0.01] #[0.0357, 0.1621, 0.0054] #[0.223, 0.0847, 0.0082]  #[0.123, 0.0447, 0.0042]
  Dyn_gp_task_noises : 
    val : [1.4, 1.48, 0.515]
    multiplier : 1.0e-6                     #1.0e-5 Low noise value make it crazy fast
  Dyn_gp_beta : 3.0 # 1.5
  mean_shift_val : 2
  cov_module: 'Matern'     #'Matern', Sq_exp
  num_dyn_samples: 5     
  mean_as_dyn_sample: False
  true_dyn_as_sample: True        # This is for debugging, set num_dyn_samples to 1
  Dyn_gp_jitter: 1.0e-6
  Dyn_gp_variance_is_zero: -1.0 # -1 : deactivated
  Dyn_gp_min_data_dist: -1.0 # -1 : deactivated
  tight:
    use: True
    dyn_eps: 0.002
    Lipschitz: 1.0045
    w_bound: 0.000001
  shift_soln: False

visu:
  show: False

common:
  use_cuda : True
  num_MPC_itrs : 50
  dynamics_rejection: False

optimizer:
  H : 15 # horizon
  u_min : [-0.6, -2] # Minimum control input
  u_max : [0.6, 2] 
  # u_min : [-30, -30] # Minimum control input
  # u_max : [30, 30] 
  x_min : [-2.14, -5.0, -0.8, 5] # Minimum state value
  x_max : [ 70, 13.0, 0.8, 12] # x,y,v,theta,theta_dot
  # x_max : [ 70, 6.0, 1.14, 10] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 7
    tol_nlp: 1.0e-4 
  order: 2
  dt: 0.06 # 0.010
  w: 40
  Qx: [2, 36, 0.07, 0.005] # n=40 [2, 32, 0.1, 0.05], n=20 [2, 32, 0.07, 0.005]
  # Qx: [2, 38, 0.11, 0.005] # n=40 [2, 32, 0.1, 0.05], n=20 [2, 32, 0.07, 0.005]
  Qu: [20, 2]
  cost: "expected"
  options: {
    levenberg_marquardt: 1.0e-1
  }
  # tightening:
  #   x_tight: [0.1, 0.1, 0.2, 0.1] #
  #   u_tight: [0.1, 0.1]

experiment:
  name: "DEMPC" #
  generate_regret_plot : True
  folder: "car"
  rnd_seed: 
    use: True
    value: 123456

    # array([[ 4.18292227e-02,  1.99853867e-04,  5.78857959e-03,
    #      3.21057040e-02],
    #    [ 1.99853867e-04,  5.96432944e-03,  7.78279091e-03,
    #     -7.49461847e-04],
    #    [ 5.78857959e-03,  7.78279091e-03,  1.57638148e+00,
    #      1.43236896e-02],
    #    [ 3.21057040e-02, -7.49461847e-04,  1.43236896e-02,
    #      1.37260290e-01]]),
    # array([[-0.00664596, -0.005348  , -0.75699781, -0.00216248],
    #    [-0.28551   ,  0.00543966,  0.00649901, -0.69907884]])]