env:
  start: [0.0, 0.0, 0.0, 0.0] # x,y,theta,v
  dynamics: 'bicycle' # "pendulum"
  params: 
    lf: 1.105
    lr: 1.738
  prior_dyn_meas: True 
  train_data_has_derivatives: True
  n_data_x: 3
  n_data_u: 5

agent:
  g_dim :
    ny : 3
    nx : 2
    nu : 1
  dim :
    ny : 3
    nx : 4
    nu : 2
  Dyn_gp_lengthscale :
    y1 : [5.2649, 4.5967, 7.0177] # y1 : [5.2649, 4.5967, 7.0177] #[2.6384, 2.5857, 2.5669]
    y2 : [3.9696, 2.1265, 6.6749] # y2 : [3.9696, 2.1265, 6.6749] #[2.1422, 2.7733, 2.1221]
    both : [[[2.1266, 5.6651, 10.5719]], [[2.2651, 4.6306, 7.6728]], [[20.9180, 6.1829, 3.7340]]]
  Dyn_gp_noise : 7.0e-9
  Dyn_gp_outputscale : 
    y1 : 0.1040 #0.3040 #0.75  #0.65
    y2 : 0.1071 #0.3071 #0.65 #0.455, noise multiplier 3.0e-7 results in smooth trajectories
    both : [0.123, 0.0447, 0.0042]
  Dyn_gp_task_noises : 
    val : [1.4, 0.48, 1.47, 0.515]
    multiplier : 1.0e-5                     #1.0e-5 Low noise value make it crazy fast
  Dyn_gp_beta : 3.0 # 1.5
  mean_shift_val : 2
  cov_module: 'Matern'     #'Matern', Sq_exp
  num_dyn_samples: 10      
  mean_as_dyn_sample: False
  true_dyn_as_sample: False        # This is for debugging, set num_dyn_samples to 1

visu:
  show: False
  show_current_loc: False

common:
  use_cuda : True
  num_MPC_itrs : 100

optimizer:
  H : 20 # horizon
  u_min : [-0.5, -2] # Minimum control input
  u_max : [0.5, 2] 
  # u_min : [-30, -30] # Minimum control input
  # u_max : [30, 30] 
  x_min : [-2.14, -1, -2.3, -2] # Minimum state value
  x_max : [ 3.14, 1, 2.3, 2] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 5
    tol_nlp: 1.0e-4 
  Tf: 1  # sampling time = Tf/H
  order: 2
  dt: 0.015 # 0.010
  w: 50
  cost: "expected"

experiment:
  name: "DEMPC" #
  generate_regret_plot : True
  folder: "car"
  rnd_seed: 
    use: True
    value: 123456