env:
  start: [0.0, 0.0]

agent:
  dynamics: 'bicycle' # "unicycle", "bicycle", "NH_intergrator" , "int"
  Dyn_gp_lengthscale :
    y1 : [5.2649, 4.5967, 7.0177] # y1 : [5.2649, 4.5967, 7.0177] #[2.6384, 2.5857, 2.5669]
    y2 : [3.9696, 2.1265, 6.6749] # y2 : [3.9696, 2.1265, 6.6749] #[2.1422, 2.7733, 2.1221]
    both : [[[5.2649, 4.5967, 7.0177]], [[3.9696, 2.1265, 6.6749]] ]
  Dyn_gp_noise : 0.00007
  Dyn_gp_outputscale : 
    y1 : 0.65 #0.3040 #0.75
    y2 : 0.55 #0.3071 #0.65
    both : [0.65, 0.55]
  Dyn_gp_task_noises : [0.000007, 0.00001]
  Dyn_gp_beta : 1.5 # 1.5
  mean_shift_val : 2
  cov_module: 'Matern'     #'Matern', Sq_exp
  num_dyn_samples: 10
  prior_dyn_meas: True       
  mean_as_dyn_sample: False
  true_dyn_as_sample: False        # This is for debugging, set num_dyn_samples to 1

visu:
  show: False
  show_current_loc: False
  step_size: 0.02

common:
  dim : 2
  use_cuda : True
  num_MPC_itrs : 50

optimizer:
  H : 30 # horizon
  Hm : 5 # somewhere in the middle of the horizon
  u_min : [-8] # Minimum control input
  u_max : [8] 
  # u_min : [-30, -30] # Minimum control input
  # u_max : [30, 30] 
  x_min : [-2.14, -2.5] # Minimum state value
  x_max : [ 2.14, 2.5] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 2
    tol_nlp: 1.0e-4 
  Tf: 1  # sampling time = Tf/H
  order: 2
  x_dim: 2
  dt: 0.015 # 0.010
  w: 50
  cost: "expected"

algo:
  objective: "DE" # "GO" "SE" 
  strategy: "SEpessi" # "optiTraj" #"goose" #"SEpessi" # "SEopti" # Heustic to select a high level goal
  type: "MPC_expander" #  "ret", "ret_expander", "MPC_expander", "MPC", "MPC_Xn", "MPC_V0"
  init: "discrete" # past_iterate discrete

experiment:
  name: "DEMPC" #
  generate_regret_plot : True
  folder: "pendulum"
  rnd_seed: 
    use: True
    value: 123456